[project]
name = "til-app"
version = "1.0.0"
description = "fastapi 기반의 TIL 기록 웹 애플리케이션"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "alembic>=1.18.0",
    "dependency-injector>=4.48.3",
    "fastapi>=0.128.0",
    "mysqlclient>=2.2.7",
    "passlib[bcrypt]>=1.7.4",
    "py-ulid>=1.0.3",
    "pydantic[email]>=2.12.5",
    "pymysql>=1.1.2",
    "sqlalchemy>=2.0.45",
    "uvicorn[standard]>=0.40.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "mypy>=1.19.0",
    "poethepoet>=0.38.0",
    "pytest>=9.0.2",
    "ruff>=0.14.8",
    "types-requests>=2.32.4.20250913",
]

[tool.uv.build-backend]
namespace = true

[tool.mypy]
pretty = true
warn_unused_ignores = true
show_error_context = true
warn_incomplete_stub = true
ignore_missing_imports = true
check_untyped_defs = true
cache_dir = "/dev/null"
warn_redundant_casts = true
warn_unused_configs = true
strict_optional = true

[tool.ruff]
line-length = 88
indent-width = 4
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["D100", "D104", "E203", "E266", "E501", "E402", "E261", "F541"]
preview = true

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
# black compatible
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = false

[tool.poe.tasks]
_clean1 = "find . -type f -name '*.py[co]' -delete"
_clean2 = "find . -type d -name '__pycache__' -delete"
clean = ["_clean1", "_clean2"]

_black = "ruff format user/ utils/"
_isort = "ruff check --select I --fix user/ utils/"
format = ["_black", "_isort"]

_flake8 = "ruff check user/ utils/"
_mypy = "mypy user/ utils/ --explicit-package-bases"
lint = ["_flake8", "_mypy"]

# doc = "ruff check user/ utils/ --select=D101,D102,D103,D107,D201,D202,D204,D300,D414,D417,D419"

# test = "python -m pytest test/"

# all = ["format", "lint", "doc", "test", "clean"]
all = ["format", "lint", "clean"]

docker_build = "docker build -t til:latest -f Dockerfile ."
docker_run = "docker run --env-file .env.dev --name til-container til:latest"

docker_first_run_db = "docker run --name mysql-local -p 3306:3306/tcp -e MYSQL_ROOT_PASSWORD=test -d mysql:8"
docker_run_db = "docker start mysql-local"

[virtualenvs]
in-project = true
